# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies including dev
COPY package.json package-lock.json tsconfig.json ./
RUN npm install

# Copy source and build
COPY src ./src
RUN npm run build

# Final image
FROM node:lts-alpine
WORKDIR /app
ENV NODE_ENV=production

# Copy build output and package files
COPY package.json package-lock.json ./
COPY --from=builder /app/dist ./dist

# Install only prod
RUN npm install --omit=dev --omit=optional

# Expose nothing (stdio)

# Default entrypoint
ENTRYPOINT ["node", "dist/index.js"]
